### ISSUE TITLE
Type of detectEncoding should be only string if no options

### ISSUE THREAD

**Issue by JSteunou** [GlobalSport/char-encoding-detector#1]
Hi there, kudos for this marvel, really a savior!

Could it be possible to fix the return type of detectEncoding & detectFileEncoding to be only `string` and not `IMatch[] | string` when no options provide.

With `IMatch[] | string` we are force to cast into `string` when using detect at its simplest way :)

**Comment by damiengarbarino** [comment]
Hi,

Thanks, nearly all the credits go to the author of node-chardet.

I cannot change the return type of the detectEncoding function as it can return either a string or a list of matches and I wanted to have the same main API than node-chardet.

But I added helper functions in 0.0.8 that should help you (see README.md).

Regards,

Damien

**Comment by JSteunou** [comment]
I appreciate the effort but I have 2 concerns with those changes: 

1. Typing depending on arguments / number of arguments can be done with function overloading

defining twice the function signature is completely valid and the way to go in TypeScript

```ts
detectFileEncoding(file: File) : Promise<string>
detectFileEncoding(file: File, options: Options) : Promise<string | IMatch[]> {
    return readFileContentsAsUint8Array(file).then((content) => detectEncoding(content, opts));
}
```

~~introducing `const` & `let` instead of `var` might be a breaking change for those using this library with old browsers like IE :(~~

Update : forget about my last concern, I did not see the files where transpile with babel before publish on npm :+1:

**Comment by damiengarbarino** [comment]
Hi,

Indeed, I'm not using this feature of TS so I forgot it but you're right, we can use function overloading.

I deployed the 0.0.9 version to address this.
